import { SuppressHydrationWarning } from "@/shared/components/suppress-hydration-warning";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";

const mulish = Mulish({
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${mulish.className} dark antialiased`}
        suppressHydrationWarning={true}
      >
        <ClerkProvider
          appearance={{
            baseTheme: dark,
          }}
        >
          <SuppressHydrationWarning>
            <div className="flex h-full flex-col overflow-hidden">
              {children}
            </div>
          </SuppressHydrationWarning>
        </ClerkProvider>
      </body>
    </html>
  );
}
